name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      # Install dependencies
      - run: cd backend && npm install

      # Check ALL .js files at once for missing modules & syntax errors
      - run: find backend -name "*.js" -not -path "*/node_modules/*" | xargs -I {} node --check {}

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: cd frontend && npm install && npm run build


  # python:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Setup Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.11'
  #     - run: cd backend/python && pip install -r requirements.txt && pytest